[package]
name = "chapter_14"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
resolver = "3"
members = [ "add_one","adder"]

[dependencies]
